name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019]
        java: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        java-package: jdk
        cache: maven
        mvn-toolchain-id: ${{ matrix.java }}
    - name: Setup minimum Java version
      if: ${{ matrix.java < 8 }}
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
        java-package: jdk
    - name: Setup GPG
      run: gpg --batch --passphrase '' --quick-gen-key "John Doe <johndoe@x.y>" ed25519 sign 1d
    - name: Available toolchains
      run: cat $HOME/.m2/toolchains.xml
    - name: Java version
      run: java -version && javac -version
    - name: Build
      if: ${{ matrix.java >= 8 }}
      run: ./mvnw install -Prelease
    - name: Build
      if: ${{ matrix.java < 8 }}
      run: ./mvnw install -Prelease -Djdk=${{ matrix.java }}
